apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  REDIS_URL: redis://{{.Values.redisServer.name}}:6379/
  {{- range .Values.configMap.data}}
  {{ . | toYaml}}
  {{- end }}
