apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisServer.name }}
  labels:
    {{- template "app_label" . }}
    {{- include "redis_tier" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6379
  selector:
    {{- template "app_label" . }}
    {{- include "redis_tier" . }}
