apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.railsServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- template "app_label" . }}
    {{- template "api_tier"}}
  ports:
    - port: 80
      targetPort: 3000
