apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.workers.name }}
  labels:
    {{- template "app_label" .}}
    {{- template "sidekiq_tier"}}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      {{- include "app_label" . | indent 2}}
      {{- include "sidekiq_tier" . | indent 2}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "app_label" . | indent 4}}
        {{- include "sidekiq_tier" . | indent 4}}
    spec:
      imagePullSecrets:
      - name: {{ .Values.dockerCredentialSecretName }}
      containers:
      - image: {{ .Values.dockerAccountName }}/{{ .Values.image.name }}:{{.Values.image.tag}}
        name: sidekiq
        command: ["bundle", "exec", "sidekiq"]
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
        - configMapRef:
            name: {{ .Values.configMap.name }}
